{% set name = "meld" %}
{% set version = "0.4.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maccallumlab/meld/archive/refs/tags/{{ version }}.tar.gz
  sha256: ba4f3be51f7be573223b29af7e601f90169332ddef25f6479a00bd168ab43a82

build:
  number: 0
  skip: true  # [cuda_compiler_version in (undefined, 'None') or win or osx]
  missing_dso_whitelist:
    - "*/libcuda.*"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ cdt('mesa-libgl-devel') }}
    - cmake
    - make

  host:
    - python
    - pip
    - swig
    - openmm
    - eigen

  run:
    - python
    - {{ pin_compatible('openmm',  min_pin='x.x', max_pin='x.x') }}
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - ambertools
    - parmed
    - tqdm

test:
  requires:
    - mpich
    - mpi4py
  imports:
    - meld
  commands: |
    test -f $PREFIX/lib/libMeldPlugin.so
    test -f $PREFIX/lib/plugins/libMeldPluginCUDA.so
    python -m unittest discover meld.test

about:
  home: https://github.com/maccallumlab/meld
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: 'Modeling Employing Limited Data'
  description: |
    MELD is a GPU-accelerated framework for integratie structural biology.
  doc_url: https://github.com/maccallumlab/meld
  dev_url: https://github.com/maccallumlab/meld

extra:
  recipe-maintainers:
    - jlmaccal
