{% set name = "meld" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maccallumlab/meld/archive/refs/tags/{{ version }}.tar.gz
  sha256: aae8e5bfbdacc1e6de61768a3298314c51575cda477a511e98dc11f5730fd918

build:
  number: 0
  skip: true  # [cuda_compiler_version in (undefined, 'None') or win or osx]
  missing_dso_whitelist:
    - '*/libcuda.*'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ cdt('mesa-libgl-devel') }}
    - cmake
    - make

  host:
    - python
    - pip
    - swig
    - openmm >=7.7.0
    - eigen
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - ambertools
    - parmed
    - progressbar

  run:
    - python
    - {{ pin_compatible('openmm',  min_pin='x.x', max_pin='x.x') }}
    - numpy
    - scipy
    - hdf4
    - netcdf4
    - ambertools
    - parmed
    - progressbar
    - openmm >=7.7.0

test:
  requires:
    - mpich
    - mpi4py
  imports:
    - meld
  commands: |
    test -f $PREFIX/lib/libMeldPlugin.so
    test -f $PREFIX/lib/plugins/libMeldPluginCUDA.so
    python -m unittest discover meld.test

about:
  home: https://github.com/maccallumlab/meld
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: Modeling Employing Limited Data
  description: |
    MELD is a GPU-accelerated framework for integratie structural biology.
  doc_url: https://github.com/maccallumlab/meld
  dev_url: https://github.com/maccallumlab/meld

extra:
  recipe-maintainers:
    - jlmaccal
